name: Firebase Deploy
run-name: Deploy to Firebase Hosting
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [latest]
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm run build
            - name: Deploy
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --only hosting
