name: Firebase Deploy
run-name: Deploy to Firebase Hosting
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [latest]
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
            - name: Install dependencies
              run: pnpm install --no-frozen-lockfile
            - name: Build
              run: pnpm run build
            - name: Archive Build
              uses: actions/upload-artifact@v2
              with:
                  name: build
                  path: build
    deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Download Build
              uses: actions/download-artifact@v2
              with:
                  name: build
                  path: build
            - uses: actions/checkout@v2
            - uses: lowply/deploy-firebase@v0.0.5
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
                  FIREBASE_PROJECT: name-of-the-project
