name: Firebase Deploy
run-name: Deploy to Firebase Hosting
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: pnpm build
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to Firebase Hosting
              run: firebase deploy
